"""GyroCompass CLI — architecture guardrails for AI coding agents.

Entry point: ``gyro``  (also exposed as ``gyrocompass`` in pyproject.toml).

Commands
--------
gyro init      — initialise .gyro/ in a repository
gyro analyze   — index the codebase and show architecture summary
gyro drift     — detect drift against the baseline .gyrostate.yaml
gyro mcp       — start / query the MCP server
gyro spec      — manage specs / components interactively
gyro status    — show current configuration and state
"""

from __future__ import annotations

import json
import os
import sys
from enum import Enum
from pathlib import Path
from typing import Annotated, Optional

import typer
import yaml
from loguru import logger
from rich.console import Console
from rich.panel import Panel
from rich.progress import BarColumn, Progress, SpinnerColumn, TaskProgressColumn, TextColumn
from rich.table import Table
from rich.text import Text

from gyrocompass import __version__

# ── Console singleton ──────────────────────────────────────────────────────────

console = Console()

# ── Colour palette ─────────────────────────────────────────────────────────────

_SEVERITY_STYLE: dict[str, str] = {
    "critical": "bold red",
    "high": "bold orange3",
    "medium": "bold yellow",
    "low": "bold blue",
    "info": "dim",
    "ok": "bold green",
}

# ── Typer app ──────────────────────────────────────────────────────────────────

app = typer.Typer(
    name="gyro",
    help="GyroCompass — architecture guardrails for AI coding agents.",
    add_completion=False,
    no_args_is_help=True,
    rich_markup_mode="rich",
)

# ── Output format enum ─────────────────────────────────────────────────────────


class OutputFormat(str, Enum):
    json = "json"
    markdown = "markdown"
    table = "table"


class LLMProvider(str, Enum):
    openai = "openai"
    anthropic = "anthropic"
    ollama = "ollama"
    custom = "custom"


# ── Helpers ────────────────────────────────────────────────────────────────────


def _resolve_repo(repo: str | None) -> Path:
    """Return an absolute repo path, defaulting to CWD."""
    return Path(repo).resolve() if repo else Path.cwd()


def _load_state(repo_path: Path):
    """Load ArchitectureState from .gyrostate.yaml.  Exits with error if missing."""
    from gyrocompass.config import get_state_path

    state_path = get_state_path(repo_path)
    if not state_path.exists():
        console.print(
            Panel(
                f"[bold red]No baseline found.[/]\n\n"
                f"Expected: [bold]{state_path}[/]\n\n"
                "Run [bold cyan]gyro init[/] and then [bold cyan]gyro analyze --save[/] first.",
                title="[red]Error[/]",
                border_style="red",
            )
        )
        raise typer.Exit(code=1)

    from gyrocompass.models import ArchitectureState

    with state_path.open(encoding="utf-8") as fh:
        raw = yaml.safe_load(fh)
    return ArchitectureState.model_validate(raw)


def _load_rules(repo_path: Path):
    """Load Rules from .gyrorules.yaml.  Returns empty Rules if file absent."""
    from gyrocompass.config import get_rules_path
    from gyrocompass.models import Rules

    rules_path = get_rules_path(repo_path)
    if not rules_path.exists():
        return Rules()
    with rules_path.open(encoding="utf-8") as fh:
        raw = yaml.safe_load(fh) or {}
    return Rules.model_validate(raw)


def _load_config(repo_path: Path) -> dict:
    """Load project config.yaml.  Returns {} if not found."""
    from gyrocompass.config import GYROCONFIG_FILE

    cfg_path = repo_path / GYROCONFIG_FILE
    if not cfg_path.exists():
        return {}
    with cfg_path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _suppress_loguru() -> None:
    """Remove the default loguru handler so only rich output appears in CLI."""
    logger.remove()


# ── init ───────────────────────────────────────────────────────────────────────

_GYROSTATE_TEMPLATE = """\
# .gyrostate.yaml — baseline architecture snapshot
# Generated by GyroCompass.  Edit carefully; run `gyro analyze --save` to refresh.
metadata:
  version: "1.0"
  serial: 1
  project: "{project_name}"
  captured_at: null  # will be set on first analyze --save

architecture: {{}}
data_model:
  entities: {{}}
capabilities: {{}}
tech_stack: {{}}
surface_area: {{}}
services: {{}}
"""

_GYRORULES_TEMPLATE = """\
# .gyrorules.yaml — architecture rules and invariants
# GyroCompass uses this to detect rule violations in PRs.

principles: {}
  # example:
  # no-direct-db-access:
  #   description: "Business logic must not directly import database models"
  #   status: active
  #   scope: ["src/services/**"]
  #   evidence:
  #     - pattern: "from.*models.*import"
  #       type: code_pattern
  #       description: "Move DB access into a repository layer"

adrs: {}
  # example:
  # adr-001-use-fastapi:
  #   title: "Use FastAPI for the HTTP layer"
  #   status: accepted
  #   date: "2024-01-01"
  #   context: "We need a fast, async-capable Python web framework."
  #   decision: "We will use FastAPI."
  #   consequences: ["OpenAPI docs are auto-generated", "Requires Pydantic models"]

invariants: {}
  # example:
  # no-eval-usage:
  #   description: "eval() must never be used in production code"
  #   status: active
  #   enforcement: block
  #   scope: ["src/**"]
  #   evidence:
  #     - pattern: "\\beval\\s*\\("
  #       type: code_pattern
  #       description: "Replace eval() with a safe alternative"
"""

_GYROCONFIG_TEMPLATE = """\
# .gyro/config.yaml — GyroCompass project configuration
project:
  name: "{project_name}"
  description: ""
  github_repo: null

llm:
  provider: "{llm_provider}"
  model: null  # leave null to use the provider default

indexing:
  exclude_paths:
    - node_modules
    - .git
    - __pycache__
    - .venv
    - venv
    - dist
    - build
    - .next
    - target

github:
  webhook_secret_env: GITHUB_WEBHOOK_SECRET
  token_env: GITHUB_TOKEN
"""


@app.command()
def init(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    name: Annotated[Optional[str], typer.Option("--name", "-n", help="Project name.")] = None,
    llm_provider: Annotated[LLMProvider, typer.Option("--llm-provider", help="LLM provider to use.")] = LLMProvider.openai,
    analyze: Annotated[bool, typer.Option("--analyze", help="Run initial analysis after init.")] = False,
) -> None:
    """Initialise .gyro/ in a repository with config and template files."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    console.print()
    console.print(
        Panel(
            f"[bold cyan]GyroCompass v{__version__}[/]\n"
            "[dim]Open-source architecture guardrails for AI coding agents[/]",
            title="[bold]Welcome[/]",
            border_style="cyan",
            padding=(1, 4),
        )
    )
    console.print()

    from gyrocompass.config import GYRO_DIR, GYROCONFIG_FILE, GYRORULES_FILE, GYROSTATE_FILE

    gyro_dir = repo_path / GYRO_DIR
    gyro_dir.mkdir(exist_ok=True)

    project_name = name or repo_path.name

    # Write config.yaml
    cfg_path = repo_path / GYROCONFIG_FILE
    if not cfg_path.exists():
        cfg_path.write_text(
            _GYROCONFIG_TEMPLATE.format(
                project_name=project_name,
                llm_provider=llm_provider.value,
            ),
            encoding="utf-8",
        )
        console.print(f"  [green]Created[/]  {cfg_path.relative_to(repo_path)}")
    else:
        console.print(f"  [dim]Exists[/]   {cfg_path.relative_to(repo_path)}")

    # Write .gyrostate.yaml template
    state_path = repo_path / GYROSTATE_FILE
    if not state_path.exists():
        state_path.write_text(
            _GYROSTATE_TEMPLATE.format(project_name=project_name),
            encoding="utf-8",
        )
        console.print(f"  [green]Created[/]  {state_path.relative_to(repo_path)}")
    else:
        console.print(f"  [dim]Exists[/]   {state_path.relative_to(repo_path)}")

    # Write .gyrorules.yaml template
    rules_path = repo_path / GYRORULES_FILE
    if not rules_path.exists():
        rules_path.write_text(_GYRORULES_TEMPLATE, encoding="utf-8")
        console.print(f"  [green]Created[/]  {rules_path.relative_to(repo_path)}")
    else:
        console.print(f"  [dim]Exists[/]   {rules_path.relative_to(repo_path)}")

    console.print()
    console.print(
        Panel(
            "[bold green]Initialisation complete![/]\n\n"
            "[bold]Next steps:[/]\n"
            "  1. [cyan]gyro analyze --save[/]          — index the codebase and save the baseline\n"
            "  2. [cyan]gyro drift[/]                   — check for architectural drift\n"
            "  3. [cyan]gyro mcp start[/]               — start the MCP server for Claude / Cursor\n"
            "  4. Edit [bold].gyro/.gyrorules.yaml[/]   — add your architecture invariants\n\n"
            "[dim]Docs: https://github.com/gyrocompass-io/gyrocompass[/]",
            title="[bold green]Done[/]",
            border_style="green",
            padding=(1, 2),
        )
    )

    if analyze:
        console.print()
        # Delegate to the analyze command
        _run_analyze(repo_path=repo_path, use_llm=False, save=True)


def _ensure_gyro_initialized(repo_path: Path, project_name: str, llm_provider: str) -> list[str]:
    """Write .gyro/ templates if missing. Returns list of created file labels."""
    from gyrocompass.config import GYRO_DIR, GYROCONFIG_FILE, GYRORULES_FILE, GYROSTATE_FILE

    (repo_path / GYRO_DIR).mkdir(exist_ok=True)
    created: list[str] = []

    cfg = repo_path / GYROCONFIG_FILE
    if not cfg.exists():
        cfg.write_text(
            _GYROCONFIG_TEMPLATE.format(project_name=project_name, llm_provider=llm_provider),
            encoding="utf-8",
        )
        created.append("config.yaml")

    state = repo_path / GYROSTATE_FILE
    if not state.exists():
        state.write_text(_GYROSTATE_TEMPLATE.format(project_name=project_name), encoding="utf-8")
        created.append(".gyrostate.yaml")

    rules = repo_path / GYRORULES_FILE
    if not rules.exists():
        rules.write_text(_GYRORULES_TEMPLATE, encoding="utf-8")
        created.append(".gyrorules.yaml")

    return created


# ── setup (one-command onboarding) ──────────────────────────────────────────────


@app.command()
def setup(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    name: Annotated[Optional[str], typer.Option("--name", "-n", help="Project name.")] = None,
    llm_provider: Annotated[LLMProvider, typer.Option("--llm-provider", help="LLM provider to use.")] = LLMProvider.openai,
    llm: Annotated[bool, typer.Option("--llm", help="Enhance architecture descriptions with the LLM.")] = False,
    hooks: Annotated[bool, typer.Option("--hooks/--no-hooks", help="Install git + Claude Code enforcement hooks.")] = True,
) -> None:
    """One command to onboard a repo: init + analyze + hooks + audit summary.

    The fastest path from install to value. Detects your repo, extracts the
    architecture, installs the enforcement hooks, and shows what the ship-
    readiness audit found — all in one step.
    """
    _suppress_loguru()
    repo_path = _resolve_repo(repo)
    project_name = name or repo_path.name

    from gyrocompass import gitutils

    is_git = gitutils.is_git_repo(repo_path)

    console.print()
    console.print(
        Panel(
            f"[bold cyan]GyroCompass v{__version__}[/] — setting up [bold]{project_name}[/]\n"
            "[dim]Extract architecture · install guardrails · audit ship-readiness[/]",
            title="[bold]Setup[/]",
            border_style="cyan",
            padding=(1, 2),
        )
    )

    # ── 1. Initialize .gyro/ ─────────────────────────────────────────────────
    created = _ensure_gyro_initialized(repo_path, project_name, llm_provider.value)
    if created:
        console.print(f"  [green]✓[/] Initialized [bold].gyro/[/] ({', '.join(created)})")
    else:
        console.print("  [dim]✓[/] [dim].gyro/ already present[/]")

    # ── 2. Extract architecture ──────────────────────────────────────────────
    console.print("  [cyan]→[/] Extracting architecture from source…")
    state = None
    try:
        state = _run_analyze(repo_path=repo_path, use_llm=llm, save=True)
    except Exception as exc:  # never abort setup on a single step
        console.print(f"  [yellow]![/] analyze step had an issue: {exc}")

    # ── 3. Install enforcement hooks ─────────────────────────────────────────
    if hooks and is_git:
        try:
            from gyrocompass.hooks import installer

            installer.install_git_hooks(repo_path)
            installer.install_claude_hooks(repo_path)
            console.print("  [green]✓[/] Installed git pre-commit + Claude Code hooks")
        except Exception as exc:
            console.print(f"  [yellow]![/] could not install hooks: {exc}")
    elif hooks and not is_git:
        console.print("  [yellow]![/] not a git repo — skipped hooks (run [bold]git init[/] then [bold]gyro install-hooks[/])")

    # ── 4. Generate the interactive architecture docs ───────────────────────
    docs_html = None
    if state is not None:
        try:
            from gyrocompass.config import get_gyro_dir
            from gyrocompass.docs import DocGenerator, build_timeline_from_memory

            timeline = build_timeline_from_memory(repo_path)
            written = DocGenerator(state, timeline_items=timeline).write_all(get_gyro_dir(repo_path))
            docs_html = written.get("html")
            console.print(f"  [green]✓[/] Generated interactive docs ([bold].gyro/architecture.html[/])")
        except Exception as exc:
            console.print(f"  [yellow]![/] docs step had an issue: {exc}")

    # ── 5. Ship-readiness audit summary ──────────────────────────────────────
    audit_report = None
    try:
        from gyrocompass.audit import AuditEngine

        audit_report = AuditEngine(repo_path).run()
    except Exception as exc:
        console.print(f"  [yellow]![/] audit step had an issue: {exc}")

    # ── Summary panel ────────────────────────────────────────────────────────
    lines = ["[bold green]Setup complete![/]", ""]
    if state is not None:
        lines.append(
            f"[bold]Architecture extracted:[/] {len(state.architecture)} components · "
            f"{len(state.capabilities)} capabilities · {len(state.surface_area)} endpoints"
        )
    if audit_report is not None:
        crit, high = audit_report.critical_count, audit_report.high_count
        verdict = "[green]ship-ready[/]" if audit_report.is_ship_ready else f"[red]{crit} critical, {high} high[/]"
        lines.append(f"[bold]Audit:[/] {len(audit_report.findings)} finding(s) — {verdict}")
    if docs_html is not None:
        lines.append(f"[bold]See it:[/] open [bold].gyro/architecture.html[/] (interactive map + drift timeline)")
    lines += [
        "",
        "[bold]Next:[/]",
        "  • [cyan]gyro docs[/]                 — open the interactive architecture view",
        "  • [cyan]gyro audit -o markdown[/]   — punch list to paste into your agent",
        "  • Edit [bold].gyro/.gyrorules.yaml[/] — define your architecture invariants",
        "  • [cyan]gyro mcp start[/]            — connect Claude Code / Cursor",
        "  • Commit [bold].gyro/[/] so your team shares the same source of truth",
    ]
    console.print()
    console.print(Panel("\n".join(lines), title="[bold green]Ready[/]", border_style="green", padding=(1, 2)))


# ── analyze ────────────────────────────────────────────────────────────────────


def _run_analyze(
    repo_path: Path,
    use_llm: bool,
    save: bool,
) -> None:
    """Core analysis logic shared by `analyze` command and post-init flow."""
    from gyrocompass.config import get_state_path
    from gyrocompass.indexer import CodeIndexer

    console.print(f"[dim]Repository:[/] [bold]{repo_path}[/]")
    console.print()

    indexer = CodeIndexer(repo_path)
    state = None
    parsed_files = 0

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        console=console,
        transient=False,
    ) as progress:
        scan_task = progress.add_task("[cyan]Scanning files…", total=None)

        def _progress_cb(message: str, current: int, total: int) -> None:
            nonlocal parsed_files
            parsed_files = current
            progress.update(scan_task, description=f"[cyan]{message}", total=total or None, completed=current)

        state = indexer.index(progress_callback=_progress_cb)
        progress.update(scan_task, description="[green]Index complete", completed=100, total=100)

    console.print()

    # -- Optionally enhance with LLM --
    if use_llm:
        _enhance_with_llm(state)

    # -- Architecture summary table --
    _print_architecture_table(state)

    # -- Capabilities table --
    if state.capabilities:
        _print_capabilities_table(state)

    # -- Tech stack table --
    if state.tech_stack:
        _print_tech_stack_table(state)

    # -- Save baseline --
    if save:
        state_path = get_state_path(repo_path)
        state_path.parent.mkdir(parents=True, exist_ok=True)
        with state_path.open("w", encoding="utf-8") as fh:
            yaml.dump(
                json.loads(state.model_dump_json()),
                fh,
                default_flow_style=False,
                allow_unicode=True,
                sort_keys=False,
            )
        console.print(f"\n[bold green]Baseline saved to[/] [cyan]{state_path}[/]")

        # -- Save the file map (.gyromap.yaml) so element-scoped rules resolve --
        from gyrocompass.config import get_map_path

        file_map = getattr(indexer, "last_file_map", {}) or {}
        if file_map:
            map_path = get_map_path(repo_path)
            map_doc: dict = {"metadata": {"version": "1.0"}}
            for elem_id, mappings in file_map.items():
                map_doc[f"architecture.{elem_id}"] = [
                    {"file": fm.file, **({"methods": fm.methods} if fm.methods else {})}
                    for fm in mappings
                ]
            with map_path.open("w", encoding="utf-8") as fh:
                yaml.dump(map_doc, fh, default_flow_style=False, allow_unicode=True, sort_keys=False)
            console.print(f"[bold green]File map saved to[/] [cyan]{map_path}[/]")

    return state


@app.command()
def analyze(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    llm: Annotated[bool, typer.Option("--llm", help="Enhance descriptions with LLM.")] = False,
    save: Annotated[bool, typer.Option("--save", help="Write results to .gyro/.gyrostate.yaml.")] = False,
) -> None:
    """Index the codebase and display an architecture summary."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)
    console.print()
    console.rule("[bold cyan]GyroCompass — Code Analysis[/]")
    console.print()
    _run_analyze(repo_path=repo_path, use_llm=llm, save=save)


# ── docs (visualization) ────────────────────────────────────────────────────


@app.command()
def docs(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    open_browser: Annotated[bool, typer.Option("--open/--no-open", help="Open the interactive HTML in your browser.")] = True,
) -> None:
    """Generate interactive architecture docs: HTML (graph + drift timeline), ARCHITECTURE.md, JSON.

    The HTML is a standalone, self-contained file — open it in any browser, no
    server needed. ARCHITECTURE.md renders natively on GitHub.
    """
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    state = _load_state(repo_path)   # exits with guidance if no baseline

    from gyrocompass.config import get_gyro_dir
    from gyrocompass.docs import DocGenerator, build_timeline_from_memory

    timeline = build_timeline_from_memory(repo_path)
    out_dir = get_gyro_dir(repo_path)
    written = DocGenerator(state, timeline_items=timeline).write_all(out_dir)

    lines = ["[bold green]Architecture docs generated:[/]", ""]
    lines.append(f"  [green]✓[/] Interactive view   [bold]{written['html']}[/]")
    lines.append(f"  [green]✓[/] GitHub doc          {written['markdown']}")
    lines.append(f"  [green]✓[/] Graph JSON          {written['json']}")
    lines.append(f"  [green]✓[/] Mermaid source      {written['mermaid']}")
    if timeline:
        lines.append("")
        lines.append(f"  [dim]Drift timeline: {len(timeline)} event(s) since install[/]")
    console.print()
    console.print(Panel("\n".join(lines), title="[bold cyan]gyro docs[/]", border_style="cyan", padding=(1, 2)))

    if open_browser:
        try:
            import webbrowser

            webbrowser.open(f"file://{written['html'].resolve()}")
            console.print("[dim]Opened the interactive view in your browser.[/]")
        except Exception:
            console.print(f"[dim]Open it manually: {written['html']}[/]")


def _enhance_with_llm(state) -> None:
    """Attempt to enhance component descriptions via LLM; silently skips on error."""
    try:
        from gyrocompass.config import settings
        from gyrocompass.llm.providers import get_provider

        provider = get_provider(settings)
        console.print("[dim]Enhancing descriptions with LLM…[/]")

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console,
            transient=True,
        ) as progress:
            task = progress.add_task("[cyan]Calling LLM…", total=len(state.architecture))
            for comp_id, elem in state.architecture.items():
                prompt = (
                    f"In one sentence, describe the purpose of a software component called "
                    f"'{comp_id}' that has the following facts: {', '.join(elem.facts[:5])}."
                )
                try:
                    elem.description = provider.complete(prompt, system="Be concise. One sentence only.")
                except Exception:
                    pass
                progress.advance(task)

    except Exception as exc:
        console.print(f"[dim yellow]LLM enhancement skipped: {exc}[/]")


def _print_architecture_table(state) -> None:
    table = Table(
        title=f"[bold]Architecture — {state.metadata.project}[/]",
        show_header=True,
        header_style="bold cyan",
        border_style="dim",
        show_lines=False,
        expand=True,
    )
    table.add_column("Component", style="bold", min_width=20)
    table.add_column("Type", style="dim", width=12)
    table.add_column("Status", width=10)
    table.add_column("Tags", style="dim")
    table.add_column("Description", ratio=1)

    for comp_id, elem in sorted(state.architecture.items()):
        status_style = "green" if str(elem.status.value) == "implemented" else "yellow"
        table.add_row(
            comp_id,
            elem.type.value,
            Text(elem.status.value if elem.status else "—", style=status_style),
            ", ".join(elem.tags[:4]),
            elem.description[:80],
        )

    console.print(table)
    console.print()
    console.print(
        f"  [bold]{len(state.architecture)}[/] components  •  "
        f"[bold]{len(state.capabilities)}[/] capabilities  •  "
        f"[bold]{len(state.surface_area)}[/] API endpoints  •  "
        f"[bold]{len(state.data_model.entities)}[/] data entities"
    )


def _print_capabilities_table(state) -> None:
    table = Table(
        title="[bold]Capabilities[/]",
        show_header=True,
        header_style="bold cyan",
        border_style="dim",
        show_lines=False,
    )
    table.add_column("ID", style="bold", width=22)
    table.add_column("Status", width=10)
    table.add_column("Description", ratio=1)

    for cap_id, cap in sorted(state.capabilities.items()):
        status_style = "green" if cap.status == "active" else "yellow"
        table.add_row(
            cap_id,
            Text(cap.status, style=status_style),
            cap.description,
        )
    console.print()
    console.print(table)


def _print_tech_stack_table(state) -> None:
    table = Table(
        title="[bold]Tech Stack[/]",
        show_header=True,
        header_style="bold cyan",
        border_style="dim",
        show_lines=False,
    )
    table.add_column("Technology", style="bold", min_width=20)
    table.add_column("Type", width=12)
    table.add_column("Vendor", ratio=1)
    table.add_column("Version", width=12)

    for tech_name, item in sorted(state.tech_stack.items()):
        table.add_row(
            tech_name,
            item.type,
            item.vendor or "—",
            item.version or "—",
        )
    console.print()
    console.print(table)


# ── drift ──────────────────────────────────────────────────────────────────────


@app.command()
def drift(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    files: Annotated[Optional[list[str]], typer.Option("--files", "-f", help="Specific files to analyze (repeatable).")] = None,
    pr_number: Annotated[Optional[int], typer.Option("--pr", help="PR number (informational).")] = None,
    output: Annotated[OutputFormat, typer.Option("--output", "-o", help="Output format.")] = OutputFormat.table,
) -> None:
    """Detect architectural drift against the baseline .gyrostate.yaml."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    # Suppress decorative output for machine-readable formats (CI, GitHub Action).
    if output == OutputFormat.table:
        console.print()
        console.rule("[bold cyan]GyroCompass — Drift Detection[/]")
        console.print()

    # Load baseline
    baseline = _load_state(repo_path)
    rules = _load_rules(repo_path)

    # Run fresh analysis
    from gyrocompass.indexer import CodeIndexer

    indexer = CodeIndexer(repo_path)

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
        transient=True,
    ) as progress:
        # Always index the full working tree for the "current" state. A partial
        # index of only changed files would make every unchanged component look
        # "removed" (false 100% drift). `files` is passed to the detector only
        # to scope the rule check to what actually changed.
        task = progress.add_task("[cyan]Indexing repository…", total=None)

        def _cb(msg: str, cur: int, tot: int) -> None:
            progress.update(task, description=f"[cyan]{msg}", total=tot or None, completed=cur)

        current = indexer.index(progress_callback=_cb)

    if pr_number:
        current.metadata.serial = pr_number  # type: ignore[assignment]

    # Detect drift
    from gyrocompass.drift import DriftDetector

    detector = DriftDetector(baseline=baseline, rules=rules)
    report = detector.detect(current, changed_files=files)

    # Opportunistically enrich with call-graph blast radius (graph backend only;
    # no-op + silent when GRAPH_BACKEND=lite or Memgraph is unavailable).
    try:
        from gyrocompass.graph.enrich import enrich_drift

        report = enrich_drift(report, files or [], repo_path)
    except Exception:
        pass

    # Attach PR number if provided
    if pr_number:
        report.pr_number = pr_number

    # Persist drift into architectural memory (best-effort — never break drift output)
    try:
        from gyrocompass.memory import MemoryStore

        _mem = MemoryStore(repo_path=repo_path)
        try:
            _mem.record_drift_report(report, pr=pr_number)
        finally:
            _mem.close()
    except Exception:
        pass

    # Output
    if output == OutputFormat.json:
        console.print_json(report.model_dump_json(indent=2))
    elif output == OutputFormat.markdown:
        console.print(report.to_markdown())
    else:
        _print_drift_report(report)

    # Exit code: 1 if blocking issues detected
    if report.has_blocking_issues:
        raise typer.Exit(code=1)


def _print_drift_report(report) -> None:
    """Render a drift report as a rich table."""
    from gyrocompass.models import DriftSeverity

    # Summary panel
    score_pct = f"{report.drift_score:.0%}"
    if report.drift_score == 0.0:
        score_text = f"[bold green]{score_pct}[/]"
        border = "green"
    elif report.drift_score < 0.3:
        score_text = f"[bold yellow]{score_pct}[/]"
        border = "yellow"
    else:
        score_text = f"[bold red]{score_pct}[/]"
        border = "red"

    summary_lines = [
        f"[bold]Drift Score:[/] {score_text}",
        f"[bold]Issues:[/] {len(report.events)} total  "
        f"([bold red]{report.critical_count}[/] critical  "
        f"[bold orange3]{report.high_count}[/] high  "
        f"[bold yellow]{report.medium_count}[/] medium  "
        f"[bold blue]{report.low_count}[/] low)",
        "",
        f"[dim]{report.summary}[/]",
    ]
    console.print(
        Panel(
            "\n".join(summary_lines),
            title="[bold]Drift Summary[/]",
            border_style=border,
            padding=(1, 2),
        )
    )

    if not report.events:
        console.print("\n[bold green]No architectural drift detected.[/]\n")
        return

    # Events table
    table = Table(
        title="[bold]Drift Events[/]",
        show_header=True,
        header_style="bold cyan",
        border_style="dim",
        show_lines=True,
        expand=True,
    )
    table.add_column("Severity", width=10)
    table.add_column("Type", width=22)
    table.add_column("Title", ratio=2)
    table.add_column("Element / File", ratio=1)
    table.add_column("Suggestion", ratio=2)

    severity_order = ["critical", "high", "medium", "low", "info"]
    sorted_events = sorted(
        report.events,
        key=lambda e: severity_order.index(e.severity.value) if e.severity.value in severity_order else 99,
    )

    for event in sorted_events:
        sev = event.severity.value
        style = _SEVERITY_STYLE.get(sev, "")
        location = event.element or event.file or "—"
        if event.file and event.line:
            location = f"{event.file}:{event.line}"
        table.add_row(
            Text(sev.upper(), style=style),
            event.type.value.replace("_", " "),
            event.title,
            location,
            (event.suggested_fix or "—")[:120],
        )

    console.print()
    console.print(table)

    if report.has_blocking_issues:
        console.print(
            "\n[bold red]Blocking issues detected.[/] Resolve critical/high issues before merging.\n"
        )
    else:
        console.print("\n[bold yellow]Non-blocking issues found.[/] Review before merging.\n")


# ── mcp ───────────────────────────────────────────────────────────────────────

_mcp_app = typer.Typer(help="MCP server management.", no_args_is_help=True)
app.add_typer(_mcp_app, name="mcp")


@_mcp_app.command("start")
def mcp_start() -> None:
    """Start the GyroCompass MCP server."""
    _suppress_loguru()
    transport = os.environ.get("GYRO_MCP_TRANSPORT", "stdio")

    console.print()
    console.print(
        Panel(
            f"[bold cyan]Starting GyroCompass MCP Server[/]\n"
            f"[dim]Transport:[/] [bold]{transport}[/]\n\n"
            "[bold]Connect from Claude Code:[/]\n"
            "  Add to your Claude Code MCP settings:\n\n"
            '  [dim cyan]{"gyrocompass": {"command": "gyro", "args": ["mcp", "start"]}}[/]\n\n'
            "[bold]Connect from Cursor:[/]\n"
            "  MCP settings → Custom server → command: [dim cyan]gyro mcp start[/]",
            title="[bold]MCP Server[/]",
            border_style="cyan",
            padding=(1, 2),
        )
    )
    console.print()

    if transport == "streamable-http":
        _start_mcp_http()
    else:
        _start_mcp_stdio()


def _start_mcp_stdio() -> None:
    """Start the MCP server in stdio mode."""
    try:
        from gyrocompass.mcp.server import create_mcp_server  # type: ignore[import]

        server = create_mcp_server()
        server.run()
    except ImportError:
        console.print(
            "[bold red]MCP server module not yet initialised.[/]\n"
            "Ensure [bold]gyrocompass.mcp.server[/] is present and "
            "[bold]mcp[/] package is installed."
        )
        raise typer.Exit(code=1)


def _start_mcp_http() -> None:
    """Start the MCP server in HTTP (streamable-http) mode."""
    from gyrocompass.config import settings

    host = settings.MCP_HOST
    port = settings.MCP_PORT
    console.print(f"[dim]Listening on http://{host}:{port}/mcp[/]")

    try:
        from gyrocompass.mcp.server import create_mcp_server  # type: ignore[import]

        server = create_mcp_server()
        server.run(transport="streamable-http", host=host, port=port, path="/mcp")
    except ImportError:
        console.print(
            "[bold red]MCP server module not yet initialised.[/]\n"
            "Ensure [bold]gyrocompass.mcp.server[/] is present and "
            "[bold]mcp[/] package is installed."
        )
        raise typer.Exit(code=1)


@_mcp_app.command("status")
def mcp_status() -> None:
    """Show MCP server connection status."""
    _suppress_loguru()
    transport = os.environ.get("GYRO_MCP_TRANSPORT", "stdio")
    console.print()
    console.print(
        Panel(
            f"[bold]Transport:[/] {transport}\n"
            "[dim]Use [bold cyan]gyro mcp start[/] to launch the server.[/]",
            title="[bold]MCP Status[/]",
            border_style="cyan",
        )
    )


# ── spec ──────────────────────────────────────────────────────────────────────

_spec_app = typer.Typer(help="Manage architecture specs and components.", no_args_is_help=True)
app.add_typer(_spec_app, name="spec")


@_spec_app.command("new")
def spec_new(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r")] = None,
) -> None:
    """Interactively create a new spec component."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    console.print()
    console.print(Panel("[bold cyan]New Component Spec[/]", border_style="cyan"))
    console.print()

    comp_id: str = typer.prompt("Component ID (e.g. api/auth, services/payment)")
    comp_type: str = typer.prompt(
        "Type",
        default="component",
        show_choices=True,
    )
    description: str = typer.prompt("Description (one sentence)")
    tags_raw: str = typer.prompt("Tags (comma-separated)", default="")
    tags = [t.strip() for t in tags_raw.split(",") if t.strip()]

    from gyrocompass.config import get_state_path
    from gyrocompass.models import ArchitectureElement, ElementStatus, ElementType

    # Map type string to enum
    try:
        elem_type = ElementType(comp_type)
    except ValueError:
        elem_type = ElementType.component

    element = ArchitectureElement(
        type=elem_type,
        description=description,
        tags=tags,
        status=ElementStatus.implemented,
    )

    state_path = get_state_path(repo_path)
    if state_path.exists():
        with state_path.open(encoding="utf-8") as fh:
            raw = yaml.safe_load(fh) or {}
        raw.setdefault("architecture", {})
        raw["architecture"][comp_id] = json.loads(element.model_dump_json())
        with state_path.open("w", encoding="utf-8") as fh:
            yaml.dump(raw, fh, default_flow_style=False, allow_unicode=True, sort_keys=False)
        console.print(f"\n[bold green]Component '[cyan]{comp_id}[/]' added to[/] {state_path}")
    else:
        console.print(
            f"\n[yellow]No .gyrostate.yaml found at {state_path}.[/] "
            "Run [bold cyan]gyro init[/] first."
        )
        raise typer.Exit(code=1)


@_spec_app.command("list")
def spec_list(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r")] = None,
) -> None:
    """List all documented specs and components."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    state = _load_state(repo_path)
    console.print()
    _print_architecture_table(state)


@_spec_app.command("show")
def spec_show(
    component: Annotated[str, typer.Argument(help="Component ID to show details for.")],
    repo: Annotated[Optional[str], typer.Option("--repo", "-r")] = None,
) -> None:
    """Show detailed information for a specific component."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    state = _load_state(repo_path)

    if component not in state.architecture:
        console.print(
            f"[bold red]Component '[cyan]{component}[/]' not found.[/]\n"
            f"Available: {', '.join(sorted(state.architecture.keys())[:10])}"
        )
        raise typer.Exit(code=1)

    elem = state.architecture[component]

    details = [
        f"[bold]ID:[/] {component}",
        f"[bold]Type:[/] {elem.type.value}",
        f"[bold]Status:[/] {elem.status.value if elem.status else '—'}",
        f"[bold]C4 Depth:[/] {elem.c4_depth.value if elem.c4_depth else '—'}",
        f"[bold]Description:[/] {elem.description}",
    ]

    if elem.tags:
        details.append(f"[bold]Tags:[/] {', '.join(elem.tags)}")

    if elem.facts:
        details.append("\n[bold]Facts:[/]")
        for fact in elem.facts:
            details.append(f"  • {fact}")

    if elem.relationships:
        details.append("\n[bold]Relationships:[/]")
        for rel_key, rel in elem.relationships.items():
            details.append(f"  → [cyan]{rel.target}[/] ({rel.type.value}): {rel.description or '—'}")

    console.print()
    console.print(
        Panel(
            "\n".join(details),
            title=f"[bold cyan]{component}[/]",
            border_style="cyan",
            padding=(1, 2),
        )
    )


@_spec_app.command("add-rule")
def spec_add_rule(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r")] = None,
) -> None:
    """Interactively add a rule to .gyrorules.yaml."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    console.print()
    console.print(Panel("[bold cyan]Add Architecture Rule[/]", border_style="cyan"))
    console.print()

    rule_type: str = typer.prompt(
        "Rule type",
        default="invariant",
        show_choices=True,
    )
    rule_id: str = typer.prompt("Rule ID (e.g. no-direct-db-access)")
    description: str = typer.prompt("Description (human-readable rule)")
    enforcement: str = typer.prompt(
        "Enforcement level",
        default="warn",
        show_choices=True,
    )
    pattern: str = typer.prompt("Pattern to check (regex or import name, prefix ! to negate)")
    pattern_type: str = typer.prompt(
        "Pattern type",
        default="code_pattern",
        show_choices=True,
    )
    scope_raw: str = typer.prompt("Scope globs (comma-separated, e.g. src/**)", default="")
    scope = [s.strip() for s in scope_raw.split(",") if s.strip()]
    suggestion: str = typer.prompt("Fix suggestion")

    rule_entry = {
        "description": description,
        "status": "active",
        "enforcement": enforcement,
        "scope": scope,
        "evidence": [
            {
                "pattern": pattern,
                "type": pattern_type,
                "description": suggestion,
            }
        ],
    }

    from gyrocompass.config import get_rules_path

    rules_path = get_rules_path(repo_path)
    if rules_path.exists():
        with rules_path.open(encoding="utf-8") as fh:
            raw = yaml.safe_load(fh) or {}
    else:
        raw = {"principles": {}, "adrs": {}, "invariants": {}}

    section = f"{rule_type}s"
    raw.setdefault(section, {})
    raw[section][rule_id] = rule_entry

    with rules_path.open("w", encoding="utf-8") as fh:
        yaml.dump(raw, fh, default_flow_style=False, allow_unicode=True, sort_keys=False)

    console.print(
        f"\n[bold green]Rule '[cyan]{rule_id}[/]' added to[/] {rules_path}"
    )


# ── graph ─────────────────────────────────────────────────────────────────────

_graph_app = typer.Typer(
    help="Deep code-graph engine (Memgraph + Qdrant).",
    no_args_is_help=True,
)
app.add_typer(_graph_app, name="graph")


def _graph_unavailable_panel(detail: str = "") -> Panel:
    """Helpful panel shown when the graph extra / services are missing."""
    body = [
        "[bold red]Graph engine unavailable.[/]",
        "",
        "Install the optional dependencies:",
        "  [bold cyan]pip install gyrocompass\\[graph][/]",
        "",
        "And start the backing services:",
        "  [bold cyan]docker compose --profile graph up[/]",
    ]
    if detail:
        body += ["", f"[dim]{detail}[/]"]
    return Panel(
        "\n".join(body),
        title="[red]Graph Engine[/]",
        border_style="red",
        padding=(1, 2),
    )


@_graph_app.command("status")
def graph_status_cmd() -> None:
    """Show Memgraph / Qdrant availability and graph statistics."""
    _suppress_loguru()

    try:
        from gyrocompass.config import settings
        from gyrocompass.graph.backend import GraphBackend, graph_status
    except ImportError as exc:
        console.print()
        console.print(_graph_unavailable_panel(str(exc)))
        raise typer.Exit(code=1)

    avail = graph_status(settings.MEMGRAPH_HOST, settings.MEMGRAPH_PORT)

    def _check(ok: bool) -> str:
        return "[bold green]✓[/]" if ok else "[bold red]✗[/]"

    lines = [
        f"[bold]Backend mode:[/]    {settings.GRAPH_BACKEND}",
        "",
        f"  {_check(avail.driver_installed)}  Memgraph driver (pymgclient)",
        f"  {_check(avail.server_reachable)}  Memgraph server  "
        f"[dim]({settings.MEMGRAPH_HOST}:{settings.MEMGRAPH_PORT})[/]",
    ]
    if not avail.ok and avail.reason:
        lines.append(f"  [dim yellow]{avail.reason}[/]")

    # Qdrant config (reachability is probed lazily by the semantic layer)
    qdrant_target = settings.QDRANT_URL or f"embedded ({settings.QDRANT_PATH})"
    lines += [
        "",
        f"  [bold]Qdrant:[/]          {qdrant_target}",
        f"  [bold]Semantic search:[/] "
        f"{'[green]enabled[/]' if settings.SEMANTIC_ENABLED else '[dim]disabled[/]'}",
        f"  [bold]Embedding model:[/] {settings.EMBEDDING_MODEL}",
    ]

    # Node/edge counts when reachable
    if avail.ok:
        try:
            with GraphBackend(settings.MEMGRAPH_HOST, settings.MEMGRAPH_PORT) as backend:
                stats = backend.stats()
            lines += [
                "",
                f"  [bold]Nodes:[/]           {stats.get('nodes', 0):,}",
                f"  [bold]Edges:[/]           {stats.get('edges', 0):,}",
            ]
            by_label = stats.get("by_label") or {}
            if by_label:
                top = ", ".join(f"{k}={v}" for k, v in list(by_label.items())[:6])
                lines.append(f"  [dim]{top}[/]")
        except Exception as exc:
            lines.append(f"\n  [dim yellow]Could not read graph stats: {exc}[/]")

    border = "green" if avail.ok else "yellow"
    console.print()
    console.print(
        Panel(
            "\n".join(lines),
            title="[bold cyan]GyroCompass — Graph Engine[/]",
            border_style=border,
            padding=(1, 2),
        )
    )


@_graph_app.command("build")
def graph_build(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    clean: Annotated[bool, typer.Option("--clean/--no-clean", help="Wipe the existing graph before building.")] = True,
) -> None:
    """Build (or rebuild) the deep code graph in Memgraph."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    try:
        from gyrocompass.graph.builder import GraphBuilder
    except ImportError as exc:
        console.print()
        console.print(_graph_unavailable_panel(str(exc)))
        raise typer.Exit(code=1)

    builder = GraphBuilder(repo_path)
    avail = builder.available()
    if not avail.ok:
        console.print()
        console.print(_graph_unavailable_panel(avail.reason))
        raise typer.Exit(code=1)

    console.print()
    console.print(f"[dim]Repository:[/] [bold]{repo_path}[/]")

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
        transient=True,
    ) as progress:
        progress.add_task("[cyan]Building code graph…", total=None)
        stats = builder.build(clean=clean)

    lines = [
        "[bold green]Graph build complete.[/]",
        "",
        f"  [bold]Nodes:[/] {stats.get('nodes', 0):,}",
        f"  [bold]Edges:[/] {stats.get('edges', 0):,}",
    ]
    by_label = stats.get("by_label") or {}
    if by_label:
        top = ", ".join(f"{k}={v}" for k, v in list(by_label.items())[:8])
        lines.append(f"  [dim]{top}[/]")

    console.print()
    console.print(
        Panel(
            "\n".join(lines),
            title="[bold cyan]Graph Build[/]",
            border_style="green",
            padding=(1, 2),
        )
    )


@_graph_app.command("query")
def graph_query(
    question: Annotated[str, typer.Argument(help="Natural-language question about the codebase.")],
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
) -> None:
    """Ask a natural-language question; runs generated Cypher against the graph."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    try:
        from gyrocompass.graph.backend import GraphBackend
        from gyrocompass.graph.nl_query import NLQueryEngine
    except ImportError as exc:
        console.print()
        console.print(_graph_unavailable_panel(str(exc)))
        raise typer.Exit(code=1)

    backend = GraphBackend()
    avail = backend.available()
    if not avail.ok:
        console.print()
        console.print(_graph_unavailable_panel(avail.reason))
        raise typer.Exit(code=1)

    engine = NLQueryEngine(backend, repo_path=repo_path)

    console.print()
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
        transient=True,
    ) as progress:
        progress.add_task("[cyan]Translating question to Cypher…", total=None)
        try:
            answer = engine.ask(question)
        finally:
            backend.close()

    cypher = getattr(answer, "cypher", None) or (answer.get("cypher") if isinstance(answer, dict) else None)
    rows = getattr(answer, "results", None)
    if rows is None and isinstance(answer, dict):
        rows = answer.get("results")
    rows = rows or []

    if cypher:
        console.print(f"[dim]{cypher}[/]")
        console.print()

    if not rows:
        console.print("[dim]No results.[/]")
        return

    table = Table(
        title="[bold]Query Results[/]",
        show_header=True,
        header_style="bold cyan",
        border_style="dim",
        show_lines=False,
        expand=True,
    )
    columns = list(rows[0].keys()) if isinstance(rows[0], dict) else ["value"]
    for col in columns:
        table.add_column(str(col), ratio=1)
    for row in rows[:200]:
        if isinstance(row, dict):
            table.add_row(*[str(row.get(c, "")) for c in columns])
        else:
            table.add_row(str(row))

    console.print(table)
    console.print(f"\n[dim]{len(rows)} row(s).[/]")


@_graph_app.command("search")
def graph_search(
    query: Annotated[str, typer.Argument(help="Semantic search query (natural language or code).")],
    top_k: Annotated[int, typer.Option("--top-k", help="Number of results to return.")] = 5,
) -> None:
    """Semantic code search over the embedded code graph (Qdrant + UniXcoder)."""
    _suppress_loguru()

    try:
        from gyrocompass.graph.semantic import SemanticSearch
    except ImportError as exc:
        console.print()
        console.print(_graph_unavailable_panel(str(exc)))
        raise typer.Exit(code=1)

    searcher = SemanticSearch()
    avail = searcher.available()
    ok = avail.ok if hasattr(avail, "ok") else bool(avail)
    if not ok:
        reason = getattr(avail, "reason", "")
        console.print()
        console.print(
            Panel(
                "[bold red]Semantic search unavailable.[/]\n\n"
                "Enable it by installing the heavy extras and turning it on:\n"
                "  [bold cyan]pip install gyrocompass\\[semantic][/]\n"
                "  [bold cyan]GYRO_SEMANTIC_ENABLED=true[/] in your .env\n\n"
                "And ensure Qdrant is running:\n"
                "  [bold cyan]docker compose --profile graph up qdrant[/]"
                + (f"\n\n[dim]{reason}[/]" if reason else ""),
                title="[red]Semantic Search[/]",
                border_style="red",
                padding=(1, 2),
            )
        )
        raise typer.Exit(code=1)

    console.print()
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
        transient=True,
    ) as progress:
        progress.add_task("[cyan]Embedding query and searching…", total=None)
        results = searcher.search(query, top_k)

    results = results or []
    if not results:
        console.print("[dim]No matching code found.[/]")
        return

    table = Table(
        title=f"[bold]Semantic Search — top {len(results)}[/]",
        show_header=True,
        header_style="bold cyan",
        border_style="dim",
        show_lines=True,
        expand=True,
    )
    table.add_column("Score", width=8)
    table.add_column("Symbol", style="bold", ratio=1)
    table.add_column("Location", ratio=1)
    table.add_column("Snippet", ratio=2)

    for r in results:
        get = r.get if isinstance(r, dict) else (lambda k, d=None: getattr(r, k, d))
        score = get("score", 0.0) or 0.0
        symbol = get("name") or get("qualified_name") or get("symbol") or "—"
        location = get("path") or get("file") or get("location") or "—"
        line = get("line")
        if line:
            location = f"{location}:{line}"
        snippet = (get("snippet") or get("code") or get("text") or "")
        table.add_row(
            f"{float(score):.3f}",
            str(symbol),
            str(location),
            str(snippet)[:160],
        )

    console.print(table)


# ── memory ────────────────────────────────────────────────────────────────────

_memory_app = typer.Typer(
    help="Architectural memory — drift history, decisions, remediation.",
    no_args_is_help=True,
)
app.add_typer(_memory_app, name="memory")


@_memory_app.command("status")
def memory_status(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
) -> None:
    """Show architectural-memory statistics (nodes, edges, open work)."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    from gyrocompass.memory import MemoryStore, NodeStatus, NodeType  # noqa: F401

    store = MemoryStore(repo_path=repo_path)
    try:
        s = store.stats()
    finally:
        store.close()

    lines = [
        f"[bold]Nodes:[/]             {s['nodes']}",
        f"[bold]Edges:[/]             {s['edges']}",
        "",
        f"[bold]Open drift:[/]        {s['open_drift']}",
        f"[bold]Open remediation:[/]  {s['open_remediation']}",
        f"[bold]Decisions:[/]         {s['decisions']}",
        f"[bold]Events logged:[/]     {s['events']}",
    ]
    console.print()
    console.print(
        Panel(
            "\n".join(lines),
            title="[bold cyan]GyroCompass — Architectural Memory[/]",
            border_style="cyan",
            padding=(1, 2),
        )
    )


@_memory_app.command("ready")
def memory_ready(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
) -> None:
    """List remediation work that is ready (unblocked and open)."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    from gyrocompass.memory import MemoryStore  # noqa: F401

    store = MemoryStore(repo_path=repo_path)
    try:
        items = store.ready_remediation()
    finally:
        store.close()

    if not items:
        console.print("\n[bold green]No ready remediation work — you're clear.[/]\n")
        return

    table = Table(
        title="[bold]Ready Remediation[/]",
        show_header=True,
        header_style="bold cyan",
        border_style="dim",
        show_lines=False,
        expand=True,
    )
    table.add_column("ID", style="bold", width=14)
    table.add_column("Priority", width=8)
    table.add_column("Severity", width=10)
    table.add_column("Title", ratio=1)

    for node in items:
        sev = node.severity or "—"
        style = _SEVERITY_STYLE.get(sev, "")
        table.add_row(
            node.id,
            str(node.priority),
            Text(sev, style=style),
            node.title,
        )

    console.print()
    console.print(table)


@_memory_app.command("list")
def memory_list(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    type_: Annotated[Optional[str], typer.Option("--type", "-t", help="Filter by node type (drift_event|decision|remediation|rule).")] = None,
    status_: Annotated[Optional[str], typer.Option("--status", "-s", help="Filter by status.")] = None,
) -> None:
    """List memory nodes, optionally filtered by type and status."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    from gyrocompass.memory import MemoryStore  # noqa: F401

    store = MemoryStore(repo_path=repo_path)
    try:
        nodes = store.list_nodes(type=type_, status=status_)
    finally:
        store.close()

    if not nodes:
        console.print("\n[dim]No matching nodes.[/]\n")
        return

    table = Table(
        title="[bold]Memory Nodes[/]",
        show_header=True,
        header_style="bold cyan",
        border_style="dim",
        show_lines=False,
        expand=True,
    )
    table.add_column("ID", style="bold", width=14)
    table.add_column("Type", width=14)
    table.add_column("Status", width=12)
    table.add_column("Severity", width=10)
    table.add_column("Title", ratio=1)

    for node in nodes:
        sev = node.severity or "—"
        style = _SEVERITY_STYLE.get(sev, "")
        table.add_row(
            node.id,
            node.type,
            node.status,
            Text(sev, style=style),
            node.title,
        )

    console.print()
    console.print(table)


@_memory_app.command("log")
def memory_log(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    limit: Annotated[int, typer.Option("--limit", "-n", help="Number of recent events to show.")] = 20,
) -> None:
    """Show the recent architectural-memory activity feed."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    from gyrocompass.memory import MemoryStore  # noqa: F401

    store = MemoryStore(repo_path=repo_path)
    try:
        events = store.activity(limit)
    finally:
        store.close()

    if not events:
        console.print("\n[dim]No activity yet.[/]\n")
        return

    table = Table(
        title="[bold]Activity Feed[/]",
        show_header=True,
        header_style="bold cyan",
        border_style="dim",
        show_lines=False,
        expand=True,
    )
    table.add_column("When", width=21)
    table.add_column("Event", width=16)
    table.add_column("Node", width=14)
    table.add_column("New Value", ratio=1)

    for ev in events:
        when = (ev.get("created_at") or "")[:19]
        table.add_row(
            when,
            str(ev.get("event_type") or "—"),
            str(ev.get("node_id") or "—"),
            str(ev.get("new_value") or "—"),
        )

    console.print()
    console.print(table)


@_memory_app.command("fix")
def memory_fix(
    drift_id: Annotated[str, typer.Argument(help="ID of the drift_event to remediate.")],
    title: Annotated[str, typer.Argument(help="Title for the remediation work item.")],
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    priority: Annotated[int, typer.Option("--priority", "-p", help="Priority (0=highest .. 4=lowest).")] = 1,
) -> None:
    """Open a remediation work item linked to a drift event."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    from gyrocompass.memory import MemoryStore  # noqa: F401

    store = MemoryStore(repo_path=repo_path)
    try:
        rem = store.open_remediation_for_drift(drift_id, title, priority=priority)
    finally:
        store.close()

    console.print(
        f"\n[bold green]Remediation created[/] → [cyan]{rem.id}[/]  "
        f"[dim](priority {rem.priority})[/]\n"
    )


@_memory_app.command("resolve")
def memory_resolve(
    node_id: Annotated[str, typer.Argument(help="ID of the node to mark resolved.")],
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    comment: Annotated[Optional[str], typer.Option("--comment", "-m", help="Resolution note.")] = None,
) -> None:
    """Mark a node (drift event, remediation, …) as resolved."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    from gyrocompass.memory import MemoryStore, NodeStatus  # noqa: F401

    store = MemoryStore(repo_path=repo_path)
    try:
        store.update_status(node_id, NodeStatus.resolved.value, comment=comment)
    except KeyError:
        console.print(f"\n[bold red]No such node:[/] {node_id}\n")
        raise typer.Exit(code=1)
    finally:
        store.close()

    console.print(f"\n[bold green]Resolved[/] [cyan]{node_id}[/].\n")


# ── status ────────────────────────────────────────────────────────────────────


@app.command()
def status(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
) -> None:
    """Show current configuration status and architecture summary."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    from gyrocompass.config import (
        GYROCONFIG_FILE,
        GYRORULES_FILE,
        GYROSTATE_FILE,
        get_state_path,
        settings,
    )

    # Check file presence
    gyroconfig_exists = (repo_path / GYROCONFIG_FILE).exists()
    gyrostate_exists = get_state_path(repo_path).exists()
    gyrorules_exists = (repo_path / GYRORULES_FILE).exists()

    # Determine LLM status
    provider = settings.get_effective_llm_provider()
    model = settings.get_effective_model()

    # GitHub status
    github_ok = bool(settings.GITHUB_TOKEN or settings.GITHUB_APP_ID)

    def _check(ok: bool) -> str:
        return "[bold green]✓[/]" if ok else "[bold red]✗[/]"

    config_lines = [
        "[bold]Repository:[/] " + str(repo_path),
        "",
        f"  {_check(gyroconfig_exists)}  config.yaml",
        f"  {_check(gyrostate_exists)}  .gyrostate.yaml  {'[dim](baseline)[/]' if gyrostate_exists else '[dim yellow](run: gyro analyze --save)[/]'}",
        f"  {_check(gyrorules_exists)}  .gyrorules.yaml",
        "",
        f"  [bold]LLM Provider:[/]  {provider} / {model}",
        f"  [bold]GitHub:[/]        {'[green]connected[/]' if github_ok else '[dim]not configured[/]'}",
        f"  [bold]API Port:[/]      {settings.API_PORT}",
        f"  [bold]MCP Transport:[/] {settings.MCP_TRANSPORT}",
    ]

    console.print()
    console.print(
        Panel(
            "\n".join(config_lines),
            title=f"[bold cyan]GyroCompass v{__version__} — Status[/]",
            border_style="cyan",
            padding=(1, 2),
        )
    )

    # Show architecture summary if state exists
    if gyrostate_exists:
        try:
            state = _load_state(repo_path)
            console.print()
            _print_architecture_table(state)
        except Exception:
            pass

    if not gyroconfig_exists:
        console.print("\n[dim]Run [bold cyan]gyro init[/] to get started.[/]")


# ── Enforcement commands ────────────────────────────────────────────────────


@app.command("install-hooks")
def install_hooks(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    git: Annotated[bool, typer.Option("--git/--no-git", help="Install git pre-commit/post-commit hooks.")] = True,
    claude: Annotated[bool, typer.Option("--claude/--no-claude", help="Install Claude Code PreToolUse/PostToolUse hooks.")] = True,
) -> None:
    """Install GyroCompass enforcement hooks (git + Claude Code).

    The git pre-commit hook runs [bold cyan]gyro check[/] and blocks commits that
    violate invariants or introduce blocking drift. The Claude Code hooks feed
    architectural context to your agent before every edit.
    """
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    from gyrocompass import gitutils
    from gyrocompass.hooks import installer

    if not gitutils.is_git_repo(repo_path):
        console.print(
            Panel(
                "[bold red]Not a git repository.[/]\n\n"
                "Enforcement hooks require git. Run [bold cyan]git init[/] first.",
                title="[red]Error[/]",
                border_style="red",
            )
        )
        raise typer.Exit(code=1)

    written: list[str] = []
    if git:
        written += [str(p) for p in installer.install_git_hooks(repo_path)]
    if claude:
        written.append(str(installer.install_claude_hooks(repo_path)))

    lines = ["[bold green]Hooks installed.[/]", ""]
    for p in written:
        lines.append(f"  [green]✓[/] {p}")
    lines += [
        "",
        "[dim]Git pre-commit now runs [bold]gyro check[/] and blocks bad commits.[/]",
        "[dim]Bypass once with [bold]git commit --no-verify[/] if you must.[/]",
        "[dim]Tune strictness in [bold].gyro/config.yaml[/] under [bold]enforcement:[/].[/]",
    ]
    console.print(Panel("\n".join(lines), title="[bold cyan]GyroCompass — Enforcement[/]", border_style="cyan", padding=(1, 2)))


@app.command()
def check(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    staged: Annotated[bool, typer.Option("--staged", help="Check only staged files (pre-commit mode).")] = False,
    files: Annotated[Optional[list[str]], typer.Option("--files", "-f", help="Explicit files to check.")] = None,
) -> None:
    """Run the enforcement gate (rules + drift + attestation). Exits non-zero if blocked.

    This is what the git pre-commit hook calls. Use [bold cyan]--staged[/] to gate a commit.
    """
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    from gyrocompass.enforce import EnforcementEngine

    engine = EnforcementEngine(repo_path)

    changed: list[str] | None = None
    if files:
        changed = files
    elif staged:
        from gyrocompass import gitutils

        changed = gitutils.staged_files(repo_path)
        if not changed:
            console.print("[dim]No staged files — nothing to check.[/]")
            raise typer.Exit(code=0)

    result = engine.check(changed)
    console.print(result.to_terminal())
    raise typer.Exit(code=result.exit_code)


@app.command()
def verify(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
) -> None:
    """Verify the working attestation binds to the current staged changes."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    from gyrocompass.attestation import AttestationManager

    verdict = AttestationManager(repo_path).verify()
    if verdict.valid:
        console.print(f"[bold green]✓ Attestation valid.[/] {verdict.reason}")
        raise typer.Exit(code=0)

    lines = [f"[bold red]✗ Attestation invalid.[/] {verdict.reason}"]
    if verdict.expected_hash and verdict.actual_hash:
        lines.append(f"[dim]expected {verdict.expected_hash[:12]}…, staged is {verdict.actual_hash[:12]}…[/]")
    if verdict.unresolved:
        lines.append("[yellow]unresolved rules:[/] " + ", ".join(verdict.unresolved))
    console.print("\n".join(lines))
    raise typer.Exit(code=1)


@app.command()
def attest(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    summary: Annotated[Optional[str], typer.Option("--summary", "-m", help="Why this change was made.")] = None,
    agent: Annotated[str, typer.Option("--agent", help="Agent/author identifier.")] = "human",
    archive: Annotated[bool, typer.Option("--archive", help="Archive the working attestation for HEAD (post-commit mode).")] = False,
) -> None:
    """Create (or archive) a commit attestation bound to the staged diff."""
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    from gyrocompass import gitutils
    from gyrocompass.attestation import AttestationManager

    mgr = AttestationManager(repo_path)

    if archive:
        sha = gitutils.current_sha(repo_path)
        att = mgr.load()
        if att and sha:
            dest = mgr.archive(att, sha)
            console.print(f"[green]✓ Attestation archived:[/] {dest}")
        raise typer.Exit(code=0)

    try:
        att = mgr.new_for_staged(agent=agent, summary=summary or "")
    except gitutils.GitError as exc:
        console.print(f"[bold red]Error:[/] {exc}")
        raise typer.Exit(code=1)

    path = mgr.save(att)
    console.print(
        f"[green]✓ Attestation created[/] → {path}\n"
        f"[dim]bound to staged diff {att.staged_diff_hash[:12]}…[/]\n"
        f"[dim]Edit it to declare rule compliance, then commit.[/]"
    )


# ── audit ───────────────────────────────────────────────────────────────────


_AUDIT_CAT_STYLE = {
    "security": "bold red",
    "capability": "bold yellow",
    "tech_debt": "bold magenta",
}
_AUDIT_CAT_EMOJI = {"security": "🔴", "capability": "🟡", "tech_debt": "🟣"}


@app.command()
def audit(
    repo: Annotated[Optional[str], typer.Option("--repo", "-r", help="Path to the repository root.")] = None,
    output: Annotated[OutputFormat, typer.Option("--output", "-o", help="Output format.")] = OutputFormat.table,
    only: Annotated[Optional[list[str]], typer.Option("--only", help="Run only these scanners (secrets, pii, injection, auth, tests, ci, observability, dependencies).")] = None,
    fail_on: Annotated[str, typer.Option("--fail-on", help="Exit non-zero if findings of this severity or worse exist: critical|high|medium|low|none.")] = "none",
) -> None:
    """Audit a finished app for ship-readiness — secrets, PII, vuln deps, injection, missing tests/CI.

    Emits an agent-ready punch list you can paste into Claude Code / Cursor to fix.
    """
    _suppress_loguru()
    repo_path = _resolve_repo(repo)

    from gyrocompass.audit import AuditEngine

    engine = AuditEngine(repo_path)

    if output == OutputFormat.table:
        console.print()
        console.rule("[bold cyan]GyroCompass — Ship-Readiness Audit[/]")
        console.print()

    with console.status("[cyan]Scanning…[/]", spinner="dots") if output == OutputFormat.table else _nullctx():
        report = engine.run(only=only or None)

    if output == OutputFormat.json:
        console.print_json(report.model_dump_json(indent=2))
    elif output == OutputFormat.markdown:
        console.print(report.to_markdown())
    else:
        _print_audit_report(report)

    # Exit code policy
    sev_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    if fail_on != "none" and fail_on in sev_order:
        threshold = sev_order[fail_on]
        worst = min((sev_order[f.severity.value] for f in report.findings), default=99)
        if worst <= threshold:
            raise typer.Exit(code=1)


def _nullctx():
    from contextlib import nullcontext

    return nullcontext()


def _print_audit_report(report) -> None:
    bs = report.by_severity
    header = (
        f"[bold]{len(report.findings)}[/] finding(s) across {report.files_scanned} files  •  "
        f"[red]{report.critical_count} critical[/]  "
        f"[orange3]{report.high_count} high[/]  "
        f"[yellow]{bs['medium']} medium[/]  "
        f"[blue]{bs['low']} low[/]"
    )
    if not report.findings:
        console.print(Panel("[bold green]✅ Ship-ready.[/] No issues found by the audit checklist.",
                            border_style="green", padding=(1, 2)))
        return
    verdict = ("[bold red]🚨 Not ship-ready — fix critical/high before deploy.[/]"
               if not report.is_ship_ready else
               "[yellow]⚠️ Review lower-severity items; nothing blocking.[/]")
    console.print(Panel(f"{header}\n\n{verdict}", title="[bold]Audit Summary[/]", border_style="cyan", padding=(1, 2)))
    console.print()

    table = Table(show_header=True, header_style="bold", expand=True)
    table.add_column("", width=3)
    table.add_column("Category", width=12)
    table.add_column("Check", width=22)
    table.add_column("Finding", overflow="fold")
    table.add_column("Location", width=22, overflow="fold")

    sev_rank = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    for f in sorted(report.findings, key=lambda x: (sev_rank[x.severity.value], x.category.value)):
        cat = f.category.value
        loc = ""
        if f.file:
            loc = f.file + (f":{f.line}" if f.line else "")
        sev_dot = {"critical": "[red]●[/]", "high": "[orange3]●[/]", "medium": "[yellow]●[/]", "low": "[blue]●[/]"}[f.severity.value]
        table.add_row(
            sev_dot,
            f"[{_AUDIT_CAT_STYLE[cat]}]{_AUDIT_CAT_EMOJI[cat]} {cat.replace('_', ' ')}[/]",
            f"[dim]{f.id}[/]",
            f.message + (f"\n[green dim]→ {f.fix}[/]" if f.fix else ""),
            f"[dim]{loc}[/]",
        )
    console.print(table)
    console.print()
    console.print("[dim]Tip: [bold]gyro audit -o markdown[/] gives an agent-ready punch list to paste into Claude Code / Cursor.[/]")


# ── Version callback ───────────────────────────────────────────────────────────


def _version_callback(value: bool) -> None:
    if value:
        console.print(f"gyrocompass {__version__}")
        raise typer.Exit()


@app.callback()
def main(
    version: Annotated[
        bool,
        typer.Option("--version", "-V", callback=_version_callback, is_eager=True, help="Show version and exit."),
    ] = False,
) -> None:
    """GyroCompass — architecture guardrails for AI coding agents."""


if __name__ == "__main__":
    app()
